schalkneethling/developer-toolchest

src/data/tools.json

Add JSON file and first tool

---

src/data/schema.json
src/data/tools.json

Add repo-url

---

src/App.css
src/ui/atoms/logo/index.css
src/ui/molecules/search/index.jsx

fix: mobile layout

---

src/data/tools.json

Add Prettier playground to tools

fix: add prettier playground

---

public/index.html
src/data/tools.json

fix: add icon sets

---

src/data/tools.json

complete adding initial set of tools

---

package.json
src/App.js
yarn.lock

Add insights analytics
fix #37

fix: add insights

---

README.md
src/data/tools.json

More tools. Privacy focused analytics and sustainable web design tools.

feat: add moar tools

---

src/data/tools.json

feat: testing tools

---

src/data/tools.json

Adds Google Lighthouse to tools

adds lighthouse to tools

---

src/data/tools.json

Let me know if I missed anything. Saw the repo in zatech slack.

Added Cardbon, Squoosh and Bundlephobia

---

src/data/tools.json

Add Sarah Drasner’s hero generator

feat: add hero generator

---

.gitignore
src/App.js
src/index.js
src/ui/molecules/tags/index.jsx

Fixes insights error and key warning on tags list

fix: fix insights error

---

src/data/tools.json

Adds two new tools to the chest.
Fixes Open Doodles link
fix #54

fix: open doodles and new tools

---

src/data/tools.json

Add static site generators, regexr and pwa tools and libraries
fix #60
fix #61
fix #64

feat: add ssg, regexr and pwa tools

---

src/App.css
src/App.js
src/index.css
src/ui/molecules/card/index.jsx
src/ui/molecules/search-results/index.jsx
src/ui/molecules/search/index.jsx
src/ui/molecules/tags/index.css
src/ui/molecules/tags/index.jsx

Makes tags on search results clickable and triggers a new search.
Ensure that the search string is always lowercase.
fix #45
fix #55

feat: make tags clickable

---

src/App.js
src/ui/molecules/search/index.jsx
src/ui/molecules/suggestions/index.jsx

Adds autocomplete suggestions via native HTML `datalist` ensuring unique tags via `Set`
fix #53

feat: add datalist set

---

src/data/tools.json

Add a11y auditing and testing tools and utilities
fix #72

feat: a11y tools

---

package.json
src/App.js
src/index.js
yarn.lock

Make searches bookmarkable and shareable
fix #51

feat: bookmarkable and shareable search results

---

src/data/tools.json

Adds CSS, JavaScript, REPL, utilities and dabases
fix #79
fix #78
fix #76
fix #75
fix #74
fix #71

feat: add more tools

---

src/data/tools.json

Adds a range of new tools.
fix #81
fix #82
fix #83
fix #85
fix #87
fix #88

(feat:tools) add new tools

---

src/data/tools.json

Adds:
- RegexLearn
- Hue.tools
- Replay.io
- Veed.io

feat:tools add additional tools

---

public/index.html

Add coil.com to enable web monetization.
fix #104

chore:coil add coil

---

package.json
public/index.html
public/opensearch.xml

Adds open search configuration
fix #92

feat:site add open search

---

src/data/tools.json

feat:tools add who can use and fontesk

---

src/data/tools.json

Add the Wakamai Fondue typography tool

feat:tools - add wakamai fondue

---

src/data/tools.json

https://github.com/extrawurst/gitui is great IMHO!

Update tools.json with GitUI addition

---

src/data/tools.json

Adds Adobe accessibility colour tools and colour paletter from a11yRocks

feat:tools - add tools for working with color

---

src/data/tools.json

Adds a bunch of new tools
fix #125

feat:tools ~ add a bunch of new tools

---

.github/labels.json
.github/workflows/set-default-labels.yml
package.json
yarn.lock

Adds auto labeller to keep labels in sync with all repositories.

chore:workflows ~ add auto labeller

---

src/data/tools.json

Hi Schalk, loved the project!
This PR adds three tools I find useful and didn't see on the database.
- [Fonts in the Wild](https://www.fontsinthewild.com/): Visual library to help you find the perfect free or paid fonts for your project.
- [WhatFont](http://www.chengyinliu.com/whatfont.html): The easiest way to inspect fonts on webpages. Font information one click away.
- [All The Tags](https://allthetags.com/): All the HTML tags in one place, with links to MDN and W3C documentation.
Hope you find those useful too.
Also, I fixed a typo in the tag for Toptal HTML Arrows (id 77), it was written "sumbol", but I guess you mean "symbol codes".
Cheers!

Adds 3 tools and corrects typo

---

src/data/tools.json

chore: add tools

---

src/data/tools.json

Added some dev tools

---

src/ui/molecules/search/index.css

Stack the search fields on mobile.
fix #120

fix: stack search input and button on mobile

---

.github/workflows/auto-merge.yml

Adds `target-repo` to workflow

bug: add target-repo

---

public/index.html

Add Jitsu as part of the process for Mechanical Ink to fully embrace being an open startup.

chore: add jitsu

---

package-lock.json
package.json
playwright.config.js
src/App.css
src/App.js
src/ui/molecules/article-card/index.css
src/ui/molecules/article-card/index.jsx
src/ui/molecules/featured-articles/index.css
src/ui/molecules/featured-articles/index.jsx

Starting this of really manual and simple. This is to experiment with the usefulness
of these features articles. They will rotate to new articles every two weeks.
Part of #156

feat: first iteration of featured articles

---

CODE_OF_CONDUCT.md

Add documents from project template essentials.

Community guidelines

---

public/logos/clippy.svg
public/tools.json

Adds Clippy, a super helpful tool that helps you generate CSS clip-paths.

tool: add clippy
